TITLE: YGGDRASIL A41 / T8Y — Veteran-Core Recruitment Exclusion Field
DATE: 2026-09-22
STATUS: PREREGISTERED POPULATION-TURNOVER EXPERIMENT / NON-CANONICAL
TRACK: YGGDRASIL TRAINING T8Y / APPLICATION-A
PARENT: A40 Subtractive Support-Credit Pressure
MECHANISM PARENT: A36 Spatially Cooperative Protected Hedge Niches
BRANCH: dg1a-ar

PURPOSE

A40 established that SUBTRACTIVE support credit
creates real local erosion ordering
without the balanced false-majority
or true-reversal inertia of ZERO_CROSS_SLOW.

But A40 did not break the biased-periodic oscillator.

Therefore A41 moves exactly one causal level outward.

Committed-cell defection remains frozen
at A40 SUBTRACTIVE_SLOW.

A41 changes only how currently uncertain U cells
are recruited around surviving committed cores.

QUESTION

Is the remaining periodic attractor
being regenerated by population turnover
around a locally surviving core?

Can veteran committed cells
use their accumulated evidence depth
to inhibit nearby recruitment
to the opposing side
without preventing genuine reversal?

F41 FREEZE

Let the exact A41 implementation freeze commit be F41.

No real A41 world,
population outcome,
or scientific result
may be derived before F41 exists.

WORLD SHAPE

384 fresh post-F41 trials.

48 contexts x 8 replicas.

48 cells.
48 epochs.

Environmental families remain structurally identical
to A40.

PARENT ORGANISM

Use the full A36 organism unchanged:

A29 pulse ecology;
A30 local nonlinear cross-inhibition;
A31 refractory memory;
A34 contradiction-suppressed independent recruitment;
A35 protected H uncertainty phenotype;
A36 spatial H niche entry/release cooperation.

No A37 lineage state exists.

COMMITTED-STATE LAW

All A41 arms use A40 SUBTRACTIVE_SLOW
for committed-state defection.

rho = 3/4.

For a C-committed cell:

M_pre = max(0,B_pre).

For an S-committed cell:

M_pre = max(0,-B_pre).

PRESSURE = max(0,L_op-M_pre).

p_stay = 1/(1+(PRESSURE/(1/2))^3).

No change is permitted
to the committed-state defection law.

BASE RECRUITMENT

Preserve A40 / A34 base rates:

sup_C = .75 * pool_C + .25 * local_C;
sup_S = .75 * pool_S + .25 * local_S.

oppx_C = .75 * pool_S + .25 * local_S;
oppx_S = .75 * pool_C + .25 * local_C.

g_C = 1/(1+(oppx_C/(1/2))^3).
g_S = 1/(1+(oppx_S/(1/2))^3).

lambda_C = ETA * sup_C * g_C.
lambda_S = ETA * sup_S * g_S.
lambda_H = ETA * sup_C * sup_S.

ETA = 1/2.

H recruitment is unchanged in every arm.

CORE SNAPSHOT TIMING

For recruitment at epoch t:

1. capture B_pre at epoch start;
2. update signed B as in A40;
3. execute H release;
4. execute committed-state defection using A40 SUBTRACTIVE_SLOW;
5. form a frozen survivor-core snapshot;
6. execute U-cell recruitment.

A cell contributes to the core field
only if it is still C or S
after the epoch's defection decisions.

For margin weighting,
the surviving cell contributes
its state-aligned M_pre
from the beginning of that epoch.

Thus current adverse evidence
is not counted twice
against the same veteran support credit.

CORE RADIUS

Use exactly the existing recruitment radius:

R_core = RECRUIT_R = 3.

No new radius exists.

OCCUPANCY FIELD CONTROL

For an eligible U cell i:

Q_C_occ(i)
=
mean over radius 3
of 1[state_j = C].

Q_S_occ(i)
=
mean over radius 3
of 1[state_j = S].

Then:

lambda_C'
=
lambda_C * (1 - Q_S_occ).

lambda_S'
=
lambda_S * (1 - Q_C_occ).

lambda_H is unchanged.

This tests spatial incumbent exclusion
without evidence-depth weighting.

VETERAN-MARGIN FIELD

For an eligible U cell i:

Q_C_margin(i)
=
mean over radius 3
of 1[state_j = C] * max(0,B_pre_j).

Q_S_margin(i)
=
mean over radius 3
of 1[state_j = S] * max(0,-B_pre_j).

Then:

lambda_C'
=
lambda_C * (1 - Q_S_margin).

lambda_S'
=
lambda_S * (1 - Q_C_margin).

lambda_H is unchanged.

Because 0 <= M_pre <= 1,
both Q fields remain in [0,1].

No gain,
scale,
offset,
threshold,
or fitted parameter is added.

INTERPRETATION

A surviving C veteran core
suppresses nearby S recruitment.

A surviving S veteran core
suppresses nearby C recruitment.

The field does not force same-side recruitment.

It only prevents a short counter-pulse
from rebuilding an opposing population
too easily in the immediate neighborhood
of a surviving core.

ARMS

Exactly six arms.

D2:
D2_BASE_SUBTRACTIVE_SLOW;
D2_OCCUPANCY_EXCLUSION;
D2_MARGIN_EXCLUSION.

D3:
D3_BASE_SUBTRACTIVE_SLOW;
D3_OCCUPANCY_EXCLUSION;
D3_MARGIN_EXCLUSION.

The BASE arm is the A40 SUBTRACTIVE_SLOW mechanism
with recruitment unchanged.

No additional rho,
radius,
gain,
or threshold arms are permitted.

PRIMARY TARGET

Biased-periodic contexts:

44;
45;
46;
47.

Report oscillation separately
for each context.

BALANCED CONTROL

Contexts:

40;
41;
42;
43.

Report:

oscillation;
final majority;
false-majority rate;
no-majority occupancy.

A41 must not solve pulse chasing
by manufacturing a persistent majority
under genuinely balanced evidence.

RECRUITMENT-BOUNDARY MECHANISM MEASUREMENTS

At every biased-periodic adverse-pulse epoch,
for every eligible U cell,
record:

favored-side local core field Q_favored;
opposing-side local core field Q_opposing;
base lambda to the adverse side;
gated lambda to the adverse side;
whether the cell recruited;
which side it joined.

For MARGIN_EXCLUSION,
Q uses veteran M_pre.

For OCCUPANCY_EXCLUSION,
Q uses committed occupancy only.

Report:

mean and median Q_favored;
fraction Q_favored > 0;
mean base adverse lambda;
mean gated adverse lambda;
fractional adverse-lambda suppression;
adverse-side recruitment rate.

Also stratify adverse-side recruitment
by Q_favored quartile.

The high-Q quartile
should recruit to the adverse side less often
than the low-Q quartile
if the field is mechanistically active.

CORE-ADJACENT REBUILD METRIC

At each biased adverse-pulse onset,
freeze the favored-side committed survivor-core identities.

During that adverse burst,
measure the fraction of U recruitment events
within radius 3 of those core cells
that join the adverse side.

Report separately for:

BASE;
OCCUPANCY_EXCLUSION;
MARGIN_EXCLUSION.

This is the direct macro-mechanism diagnostic.

CORE SURVIVAL

Preserve A40 core-persistence reporting
after adverse epochs 1, 2, and 3.

A41 does not claim success
merely because the original core survives.

The key question is whether
opposing recruitment around it is reduced enough
to prevent population-level cycle closure.

TRUE REVERSAL COST

Preserve:

reversal acquisition;
old-majority loss latency;
new-majority acquisition;
median old-side M at reversal onset;
median M-to-zero latency;
signed B zero-cross latency.

Additionally report:

time from reversal onset
until opposing-side recruitment
within radius 3 of the old core
returns to at least the BASE arm's
same-context median recruitment rate.

This detects stale spatial exclusion.

PRIMARY POPULATION METRICS

For every arm report:

aggregate service;
harm rate;
overall oscillation;
biased-periodic oscillation;
balanced false-majority;
false C dominance;
false S dominance;
contradiction no-majority;
reversal acquisition;
median old-majority loss;
directional coordination;
H occupancy;
niche prevalence;
recruitment activity.

A41 MARGIN-EXCLUSION QUALIFICATION

D2_MARGIN_EXCLUSION or D3_MARGIN_EXCLUSION
is A41-QUALIFIED iff all are true:

1. overall oscillation <= 5%;

2. biased-periodic oscillation <= 10%;

3. breaks at least 50%
   of paired BASE biased-periodic oscillators;

4. biased-periodic oscillation
   is lower than paired OCCUPANCY_EXCLUSION;

5. balanced false-majority <= 10%;

6. false C dominance
   does not exceed paired BASE;

7. false S dominance
   does not exceed paired BASE;

8. reversal acquisition >= 80%;

9. median old-majority loss <= 4 epochs;

10. aggregate service >= 90%
    of paired BASE;

11. recruitment remains nondegenerate;

12. high-Q adverse-side recruitment rate
    is lower than low-Q rate;

13. core-adjacent adverse rebuild
    is lower than paired BASE;

14. all integrity probes pass.

A41_INFORMATION_GAIN

TRUE iff at least one MARGIN_EXCLUSION arm:

reduces biased-periodic oscillation
versus paired BASE;

breaks at least 25%
of paired BASE biased-periodic oscillators;

reduces core-adjacent adverse rebuild
versus paired BASE;

shows lower adverse recruitment
in the high-Q quartile than the low-Q quartile;

retains reversal acquisition >= 80%;

retains >= 90% paired BASE service;

and balanced false-majority remains <= 10%.

CAUSAL ATTRIBUTION

If MARGIN_EXCLUSION succeeds
and OCCUPANCY_EXCLUSION does not:

evidence-depth-weighted veteran topology matters,
not merely incumbent density.

If both succeed similarly:

spatial incumbent topology matters,
but accumulated evidence depth
adds little beyond occupancy.

If both reduce local adverse rebuild
but macro oscillation remains:

population turnover near the core
is not the remaining oscillator bottleneck.

If MARGIN_EXCLUSION stops oscillation
but becomes sticky on true reversal:

the spatial field persists too strongly
and must later acquire a local release mechanism.

If neither changes adverse recruitment:

the survivor core is too sparse
or too weakly positioned
to control recruitment topology.

INTEGRITY

P1:
384 trials.

P2:
48 contexts x 8 replicas.

P3:
48 cells.

P4:
48 epochs.

P5:
initial C/S/U = 12/12/24.

P6:
A36 pulse ecology unchanged.

P7:
pool decay = 3/4.

P8:
local evidence radius = 12.

P9:
Hill n = 3.

P10:
Hill K = 1/2.

P11:
recruitment radius = 3.

P12:
core field radius = 3.

P13:
ETA = 1/2.

P14:
pool normalization = 160.

P15:
A34 contradiction suppression unchanged
before the new exclusion multiplier.

P16:
A35 H hazards unchanged.

P17:
A36 niche mechanics unchanged.

P18:
D2 refractory = 2.

P19:
D3 refractory = 3.

P20:
all arms use A40 SUBTRACTIVE_SLOW committed defection.

P21:
rho exactly 3/4.

P22:
B starts at zero.

P23:
B updates every epoch for every cell.

P24:
SUBTRACTIVE pressure reads M_pre.

P25:
BASE recruitment unchanged.

P26:
OCCUPANCY Q uses only survivor committed occupancy.

P27:
MARGIN Q uses survivor committed occupancy times M_pre.

P28:
Q radius exactly 3.

P29:
lambda_C' exactly lambda_C*(1-Q_S).

P30:
lambda_S' exactly lambda_S*(1-Q_C).

P31:
lambda_H unchanged.

P32:
no new gain exists.

P33:
no new threshold exists.

P34:
no new radius exists.

P35:
no A37 lineage state exists.

P36:
no future environment enters B or Q.

P37:
no centralized confidence scalar exists.

P38:
two complete primary sweeps byte-identical.

RESEARCH DISCIPLINE

Mechanical fake-world validation
must pass twice byte-identically
before F41.

F41 must exist
before fresh A41 worlds are derived.

The 384-world primary manifest
must be bound after F41
and before primary arm execution.

No post-result
rho,
radius,
gain,
threshold,
arm,
qualification,
or world-family tuning.

PLAIN-SPEAK QUESTION

A40 showed that strong veteran cells
can survive a bad pulse longer,
but the population still flips.

A41 asks whether those veterans
can protect the neighborhood around them.

Not by forcing neighbors to agree.

Instead,
a strong surviving C core
makes it harder for a nearby uncertain cell
to be recruited into S during a short S pulse,
and vice versa.

The control asks whether
any nearby committed crowd is enough.

The main arm asks whether
old, well-supported veterans
need to count more than fresh commitments.

The test is:

CAN A SURVIVING CORE STOP
THE OPPOSING POPULATION
FROM REBUILDING AROUND IT
FAST ENOUGH TO CLOSE THE OSCILLATION CYCLE?

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.


PRE-F41 AMENDMENT 01 — OCCUPANCY VS MARGIN ATTRIBUTION AND SPATIAL FAILURE DIAGNOSTICS

DATE:
2026-09-22.

STATUS:
BOUND BEFORE F41
AND BEFORE ANY REAL A41 WORLD EXISTS.

PRIMARY CAUSAL DISTINCTION

OCCUPANCY_EXCLUSION asks:

does the mere spatial presence
of surviving committed neighbors
suppress opposing recruitment?

Every surviving committed neighbor contributes
equally through committed occupancy.

MARGIN_EXCLUSION asks:

does the accumulated evidence depth
of surviving committed neighbors
modulate that suppression?

A surviving veteran with larger aligned M_pre
contributes more to the exclusion field
than a newer or weakly supported commitment.

Because A41 signed B is bounded,
M_pre remains in [0,1].
Examples using larger arbitrary numbers
are conceptual only.

If MARGIN_EXCLUSION outperforms
OCCUPANCY_EXCLUSION on the frozen criteria:

evidence depth has a second causal use
beyond committed-state persistence.

It also acts as a local signal
that shapes recruitment topology.

If OCCUPANCY_EXCLUSION matches
MARGIN_EXCLUSION:

spatial incumbent presence is sufficient
at the recruitment boundary,
and margin weighting adds no demonstrated value there.

This does not erase A39/A40's persistence result.
It means evidence depth is not additionally useful
for this topology mechanism.

RISK 1 — MOAT / EXCESSIVE SPATIAL PROTECTION

The frozen reversal-acquisition boundary remains:

>= 80%.

A41 does not add distance decay,
Gaussian falloff,
inverse-square falloff,
or any new field-shape parameter.

If exclusion reduces reversal acquisition below 80%
or pushes old-majority loss above 4 epochs,
A41 records that as excessive spatial protection.

A distance-decay field may be justified
for a later preregistered experiment,
but it is not introduced post-result into A41.

RISK 2 — CORE / PERIPHERY DEADLOCK

A41 explicitly measures
whether exclusion creates a persistent spatial split
instead of healthy resolution.

For every epoch report:

C fraction;
S fraction;
U fraction.

For the final 8 epochs report:

mean min(C_fraction,S_fraction);
mean U fraction;
number of majority-label changes;
largest contiguous C domain;
largest contiguous S domain;
C/S interface count on the 48-cell ring.

Also retain the ordered 48-cell state snapshot
at the midpoint of every biased-periodic adverse burst.

These measurements are diagnostic only.
No new qualification threshold is inferred from them after results.

A persistent high min(C_fraction,S_fraction)
together with large opposed spatial domains
and low majority turnover
is the preregistered signature
of core/periphery deadlock.

RISK 3 — TIMESCALE DEPENDENCE

A41 intentionally contains no MEDIUM arm.

All six arms use the A40 SUBTRACTIVE_SLOW
committed-state law with rho = 3/4.

A40 already showed that MEDIUM
did not materially break the target oscillator.

Therefore A41 tests the recruitment-topology hypothesis
inside the slow-response regime only.

A41 cannot establish
that the mechanism generalizes to MEDIUM.

If A41 succeeds,
timescale generalization must be tested separately
rather than inferred.

ADDITIONAL COUNTER-PULSE TRAJECTORY MEASUREMENT

For biased-periodic contexts 44-47,
record C/S/U fractions at every epoch.

For each adverse burst report:

favored-side committed fraction at pulse onset;
minimum favored-side committed fraction during burst;
favored-side committed fraction at burst end;
recovery latency to the pre-pulse favored-side committed fraction,
or NEVER.

This separates:

core survives while periphery temporarily becomes U;

from:

the core itself continues eroding.

SPATIAL MIDPOINT SNAPSHOT

At the midpoint adverse epoch of every biased-periodic burst,
record the ordered 48-cell ring state:

C;
S;
U;
H.

Also record the corresponding
survivor-core membership mask.

This allows direct inspection
for a U moat between favored core
and opposing periphery
without changing the dynamics.

INSIDE / OUTSIDE RECRUITMENT MEASUREMENT

For every eligible U recruitment opportunity
during a biased-periodic adverse burst,
classify the cell as:

INSIDE:
within ring distance <= 3
of at least one favored-side survivor-core cell;

OUTSIDE:
not within ring distance <= 3
of any favored-side survivor-core cell.

Report separately:

opportunities;
adverse-side recruitments;
adverse-side recruitment rate;
mean base adverse lambda;
mean gated adverse lambda.

For BASE,
the same geometric classification is computed
without applying an exclusion multiplier.

This directly measures
whether exclusion suppresses opposing recruitment
where the mechanism claims it should.

OCCUPANCY VS MARGIN OSCILLATOR BREAK COUNT

For each D value report:

paired BASE biased-periodic oscillators;
number broken by OCCUPANCY_EXCLUSION;
number broken by MARGIN_EXCLUSION;
oscillators broken by both;
oscillators broken only by OCCUPANCY;
oscillators broken only by MARGIN.

This comparison is descriptive
in addition to the already frozen
MARGIN qualification requirement
that MARGIN biased-periodic oscillation
be lower than paired OCCUPANCY_EXCLUSION.

No post-result tie breaker is permitted.

PLAIN-SPEAK UPDATE

A41 is now asking two questions at once,
but in a way that keeps them separable.

First:

is it enough for an uncertain cell
to see that committed veterans are nearby?

That is OCCUPANCY.

Second:

should a deeply supported veteran
count more than a fresh commitment?

That is MARGIN.

If MARGIN wins,
the memory built in A39 and A40
has found a second job.

It is not only armor
that makes the veteran harder to knock over.

It becomes a signal
that tells the surrounding neighborhood:

this commitment has earned more local trust,
so do not rebuild the opposite side beside it
because of one short pulse.

But A41 also watches for the obvious danger.

A protective neighborhood can become a moat.

If the old core becomes so protected
that a real environmental reversal
cannot rebuild around it,
the organism has not become stable.
It has become rigid.

A41 also watches for a new failure mode:

the core stays one way,
the outer population becomes the other,
and the organism gets stuck split in two.

So success is not simply
fewer flips.

Success means:

the veteran core survives a short disturbance;

nearby opposing recruitment is selectively reduced;

the whole population stops rebuilding
the opposite army every few epochs;

balanced evidence does not manufacture a false winner;

and a real reversal can still replace
the old organization promptly.

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.


POST-F41 PRIMARY MANIFEST BINDING

DATE:
2026-09-22.

F41:
533b99503712bc37547969cf63100bd83336e69a

PRIMARY SEED:
A41-F41-533b99503712bc37547969cf63100bd83336e69a-PRIMARY

WORLD COUNT:
384.

WORLD SHAPE:
48 contexts x 8 replicas.

PRIMARY WORLD MANIFEST SHA256:
a902a20ee2222f6aebc451659d8910238a1c9ee1c74f37ee4eee69a018f761c1

STATUS:
BOUND BEFORE ANY PRIMARY ARM EXECUTION.

The manifest was derived from the frozen F41 source
after F41 existed.

No arm outcome,
population metric,
qualification result,
or scientific comparison
was observed before this binding.

The canonical DG-1R-05 primary is not consumed.

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.
