TITLE: YGGDRASIL A41 / T8Y — Veteran-Core Recruitment Exclusion Field
DATE: 2026-09-22
STATUS: PREREGISTERED POPULATION-TURNOVER EXPERIMENT / NON-CANONICAL
TRACK: YGGDRASIL TRAINING T8Y / APPLICATION-A
PARENT: A40 Subtractive Support-Credit Pressure
MECHANISM PARENT: A36 Spatially Cooperative Protected Hedge Niches
BRANCH: dg1a-ar

PURPOSE

A40 established that SUBTRACTIVE support credit
creates real local erosion ordering
without the balanced false-majority
or true-reversal inertia of ZERO_CROSS_SLOW.

But A40 did not break the biased-periodic oscillator.

Therefore A41 moves exactly one causal level outward.

Committed-cell defection remains frozen
at A40 SUBTRACTIVE_SLOW.

A41 changes only how currently uncertain U cells
are recruited around surviving committed cores.

QUESTION

Is the remaining periodic attractor
being regenerated by population turnover
around a locally surviving core?

Can veteran committed cells
use their accumulated evidence depth
to inhibit nearby recruitment
to the opposing side
without preventing genuine reversal?

F41 FREEZE

Let the exact A41 implementation freeze commit be F41.

No real A41 world,
population outcome,
or scientific result
may be derived before F41 exists.

WORLD SHAPE

384 fresh post-F41 trials.

48 contexts x 8 replicas.

48 cells.
48 epochs.

Environmental families remain structurally identical
to A40.

PARENT ORGANISM

Use the full A36 organism unchanged:

A29 pulse ecology;
A30 local nonlinear cross-inhibition;
A31 refractory memory;
A34 contradiction-suppressed independent recruitment;
A35 protected H uncertainty phenotype;
A36 spatial H niche entry/release cooperation.

No A37 lineage state exists.

COMMITTED-STATE LAW

All A41 arms use A40 SUBTRACTIVE_SLOW
for committed-state defection.

rho = 3/4.

For a C-committed cell:

M_pre = max(0,B_pre).

For an S-committed cell:

M_pre = max(0,-B_pre).

PRESSURE = max(0,L_op-M_pre).

p_stay = 1/(1+(PRESSURE/(1/2))^3).

No change is permitted
to the committed-state defection law.

BASE RECRUITMENT

Preserve A40 / A34 base rates:

sup_C = .75 * pool_C + .25 * local_C;
sup_S = .75 * pool_S + .25 * local_S.

oppx_C = .75 * pool_S + .25 * local_S;
oppx_S = .75 * pool_C + .25 * local_C.

g_C = 1/(1+(oppx_C/(1/2))^3).
g_S = 1/(1+(oppx_S/(1/2))^3).

lambda_C = ETA * sup_C * g_C.
lambda_S = ETA * sup_S * g_S.
lambda_H = ETA * sup_C * sup_S.

ETA = 1/2.

H recruitment is unchanged in every arm.

CORE SNAPSHOT TIMING

For recruitment at epoch t:

1. capture B_pre at epoch start;
2. update signed B as in A40;
3. execute H release;
4. execute committed-state defection using A40 SUBTRACTIVE_SLOW;
5. form a frozen survivor-core snapshot;
6. execute U-cell recruitment.

A cell contributes to the core field
only if it is still C or S
after the epoch's defection decisions.

For margin weighting,
the surviving cell contributes
its state-aligned M_pre
from the beginning of that epoch.

Thus current adverse evidence
is not counted twice
against the same veteran support credit.

CORE RADIUS

Use exactly the existing recruitment radius:

R_core = RECRUIT_R = 3.

No new radius exists.

OCCUPANCY FIELD CONTROL

For an eligible U cell i:

Q_C_occ(i)
=
mean over radius 3
of 1[state_j = C].

Q_S_occ(i)
=
mean over radius 3
of 1[state_j = S].

Then:

lambda_C'
=
lambda_C * (1 - Q_S_occ).

lambda_S'
=
lambda_S * (1 - Q_C_occ).

lambda_H is unchanged.

This tests spatial incumbent exclusion
without evidence-depth weighting.

VETERAN-MARGIN FIELD

For an eligible U cell i:

Q_C_margin(i)
=
mean over radius 3
of 1[state_j = C] * max(0,B_pre_j).

Q_S_margin(i)
=
mean over radius 3
of 1[state_j = S] * max(0,-B_pre_j).

Then:

lambda_C'
=
lambda_C * (1 - Q_S_margin).

lambda_S'
=
lambda_S * (1 - Q_C_margin).

lambda_H is unchanged.

Because 0 <= M_pre <= 1,
both Q fields remain in [0,1].

No gain,
scale,
offset,
threshold,
or fitted parameter is added.

INTERPRETATION

A surviving C veteran core
suppresses nearby S recruitment.

A surviving S veteran core
suppresses nearby C recruitment.

The field does not force same-side recruitment.

It only prevents a short counter-pulse
from rebuilding an opposing population
too easily in the immediate neighborhood
of a surviving core.

ARMS

Exactly six arms.

D2:
D2_BASE_SUBTRACTIVE_SLOW;
D2_OCCUPANCY_EXCLUSION;
D2_MARGIN_EXCLUSION.

D3:
D3_BASE_SUBTRACTIVE_SLOW;
D3_OCCUPANCY_EXCLUSION;
D3_MARGIN_EXCLUSION.

The BASE arm is the A40 SUBTRACTIVE_SLOW mechanism
with recruitment unchanged.

No additional rho,
radius,
gain,
or threshold arms are permitted.

PRIMARY TARGET

Biased-periodic contexts:

44;
45;
46;
47.

Report oscillation separately
for each context.

BALANCED CONTROL

Contexts:

40;
41;
42;
43.

Report:

oscillation;
final majority;
false-majority rate;
no-majority occupancy.

A41 must not solve pulse chasing
by manufacturing a persistent majority
under genuinely balanced evidence.

RECRUITMENT-BOUNDARY MECHANISM MEASUREMENTS

At every biased-periodic adverse-pulse epoch,
for every eligible U cell,
record:

favored-side local core field Q_favored;
opposing-side local core field Q_opposing;
base lambda to the adverse side;
gated lambda to the adverse side;
whether the cell recruited;
which side it joined.

For MARGIN_EXCLUSION,
Q uses veteran M_pre.

For OCCUPANCY_EXCLUSION,
Q uses committed occupancy only.

Report:

mean and median Q_favored;
fraction Q_favored > 0;
mean base adverse lambda;
mean gated adverse lambda;
fractional adverse-lambda suppression;
adverse-side recruitment rate.

Also stratify adverse-side recruitment
by Q_favored quartile.

The high-Q quartile
should recruit to the adverse side less often
than the low-Q quartile
if the field is mechanistically active.

CORE-ADJACENT REBUILD METRIC

At each biased adverse-pulse onset,
freeze the favored-side committed survivor-core identities.

During that adverse burst,
measure the fraction of U recruitment events
within radius 3 of those core cells
that join the adverse side.

Report separately for:

BASE;
OCCUPANCY_EXCLUSION;
MARGIN_EXCLUSION.

This is the direct macro-mechanism diagnostic.

CORE SURVIVAL

Preserve A40 core-persistence reporting
after adverse epochs 1, 2, and 3.

A41 does not claim success
merely because the original core survives.

The key question is whether
opposing recruitment around it is reduced enough
to prevent population-level cycle closure.

TRUE REVERSAL COST

Preserve:

reversal acquisition;
old-majority loss latency;
new-majority acquisition;
median old-side M at reversal onset;
median M-to-zero latency;
signed B zero-cross latency.

Additionally report:

time from reversal onset
until opposing-side recruitment
within radius 3 of the old core
returns to at least the BASE arm's
same-context median recruitment rate.

This detects stale spatial exclusion.

PRIMARY POPULATION METRICS

For every arm report:

aggregate service;
harm rate;
overall oscillation;
biased-periodic oscillation;
balanced false-majority;
false C dominance;
false S dominance;
contradiction no-majority;
reversal acquisition;
median old-majority loss;
directional coordination;
H occupancy;
niche prevalence;
recruitment activity.

A41 MARGIN-EXCLUSION QUALIFICATION

D2_MARGIN_EXCLUSION or D3_MARGIN_EXCLUSION
is A41-QUALIFIED iff all are true:

1. overall oscillation <= 5%;

2. biased-periodic oscillation <= 10%;

3. breaks at least 50%
   of paired BASE biased-periodic oscillators;

4. biased-periodic oscillation
   is lower than paired OCCUPANCY_EXCLUSION;

5. balanced false-majority <= 10%;

6. false C dominance
   does not exceed paired BASE;

7. false S dominance
   does not exceed paired BASE;

8. reversal acquisition >= 80%;

9. median old-majority loss <= 4 epochs;

10. aggregate service >= 90%
    of paired BASE;

11. recruitment remains nondegenerate;

12. high-Q adverse-side recruitment rate
    is lower than low-Q rate;

13. core-adjacent adverse rebuild
    is lower than paired BASE;

14. all integrity probes pass.

A41_INFORMATION_GAIN

TRUE iff at least one MARGIN_EXCLUSION arm:

reduces biased-periodic oscillation
versus paired BASE;

breaks at least 25%
of paired BASE biased-periodic oscillators;

reduces core-adjacent adverse rebuild
versus paired BASE;

shows lower adverse recruitment
in the high-Q quartile than the low-Q quartile;

retains reversal acquisition >= 80%;

retains >= 90% paired BASE service;

and balanced false-majority remains <= 10%.

CAUSAL ATTRIBUTION

If MARGIN_EXCLUSION succeeds
and OCCUPANCY_EXCLUSION does not:

evidence-depth-weighted veteran topology matters,
not merely incumbent density.

If both succeed similarly:

spatial incumbent topology matters,
but accumulated evidence depth
adds little beyond occupancy.

If both reduce local adverse rebuild
but macro oscillation remains:

population turnover near the core
is not the remaining oscillator bottleneck.

If MARGIN_EXCLUSION stops oscillation
but becomes sticky on true reversal:

the spatial field persists too strongly
and must later acquire a local release mechanism.

If neither changes adverse recruitment:

the survivor core is too sparse
or too weakly positioned
to control recruitment topology.

INTEGRITY

P1:
384 trials.

P2:
48 contexts x 8 replicas.

P3:
48 cells.

P4:
48 epochs.

P5:
initial C/S/U = 12/12/24.

P6:
A36 pulse ecology unchanged.

P7:
pool decay = 3/4.

P8:
local evidence radius = 12.

P9:
Hill n = 3.

P10:
Hill K = 1/2.

P11:
recruitment radius = 3.

P12:
core field radius = 3.

P13:
ETA = 1/2.

P14:
pool normalization = 160.

P15:
A34 contradiction suppression unchanged
before the new exclusion multiplier.

P16:
A35 H hazards unchanged.

P17:
A36 niche mechanics unchanged.

P18:
D2 refractory = 2.

P19:
D3 refractory = 3.

P20:
all arms use A40 SUBTRACTIVE_SLOW committed defection.

P21:
rho exactly 3/4.

P22:
B starts at zero.

P23:
B updates every epoch for every cell.

P24:
SUBTRACTIVE pressure reads M_pre.

P25:
BASE recruitment unchanged.

P26:
OCCUPANCY Q uses only survivor committed occupancy.

P27:
MARGIN Q uses survivor committed occupancy times M_pre.

P28:
Q radius exactly 3.

P29:
lambda_C' exactly lambda_C*(1-Q_S).

P30:
lambda_S' exactly lambda_S*(1-Q_C).

P31:
lambda_H unchanged.

P32:
no new gain exists.

P33:
no new threshold exists.

P34:
no new radius exists.

P35:
no A37 lineage state exists.

P36:
no future environment enters B or Q.

P37:
no centralized confidence scalar exists.

P38:
two complete primary sweeps byte-identical.

RESEARCH DISCIPLINE

Mechanical fake-world validation
must pass twice byte-identically
before F41.

F41 must exist
before fresh A41 worlds are derived.

The 384-world primary manifest
must be bound after F41
and before primary arm execution.

No post-result
rho,
radius,
gain,
threshold,
arm,
qualification,
or world-family tuning.

PLAIN-SPEAK QUESTION

A40 showed that strong veteran cells
can survive a bad pulse longer,
but the population still flips.

A41 asks whether those veterans
can protect the neighborhood around them.

Not by forcing neighbors to agree.

Instead,
a strong surviving C core
makes it harder for a nearby uncertain cell
to be recruited into S during a short S pulse,
and vice versa.

The control asks whether
any nearby committed crowd is enough.

The main arm asks whether
old, well-supported veterans
need to count more than fresh commitments.

The test is:

CAN A SURVIVING CORE STOP
THE OPPOSING POPULATION
FROM REBUILDING AROUND IT
FAST ENOUGH TO CLOSE THE OSCILLATION CYCLE?

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.


PRE-F41 AMENDMENT 01 — OCCUPANCY VS MARGIN ATTRIBUTION AND SPATIAL FAILURE DIAGNOSTICS

DATE:
2026-09-22.

STATUS:
BOUND BEFORE F41
AND BEFORE ANY REAL A41 WORLD EXISTS.

PRIMARY CAUSAL DISTINCTION

OCCUPANCY_EXCLUSION asks:

does the mere spatial presence
of surviving committed neighbors
suppress opposing recruitment?

Every surviving committed neighbor contributes
equally through committed occupancy.

MARGIN_EXCLUSION asks:

does the accumulated evidence depth
of surviving committed neighbors
modulate that suppression?

A surviving veteran with larger aligned M_pre
contributes more to the exclusion field
than a newer or weakly supported commitment.

Because A41 signed B is bounded,
M_pre remains in [0,1].
Examples using larger arbitrary numbers
are conceptual only.

If MARGIN_EXCLUSION outperforms
OCCUPANCY_EXCLUSION on the frozen criteria:

evidence depth has a second causal use
beyond committed-state persistence.

It also acts as a local signal
that shapes recruitment topology.

If OCCUPANCY_EXCLUSION matches
MARGIN_EXCLUSION:

spatial incumbent presence is sufficient
at the recruitment boundary,
and margin weighting adds no demonstrated value there.

This does not erase A39/A40's persistence result.
It means evidence depth is not additionally useful
for this topology mechanism.

RISK 1 — MOAT / EXCESSIVE SPATIAL PROTECTION

The frozen reversal-acquisition boundary remains:

>= 80%.

A41 does not add distance decay,
Gaussian falloff,
inverse-square falloff,
or any new field-shape parameter.

If exclusion reduces reversal acquisition below 80%
or pushes old-majority loss above 4 epochs,
A41 records that as excessive spatial protection.

A distance-decay field may be justified
for a later preregistered experiment,
but it is not introduced post-result into A41.

RISK 2 — CORE / PERIPHERY DEADLOCK

A41 explicitly measures
whether exclusion creates a persistent spatial split
instead of healthy resolution.

For every epoch report:

C fraction;
S fraction;
U fraction.

For the final 8 epochs report:

mean min(C_fraction,S_fraction);
mean U fraction;
number of majority-label changes;
largest contiguous C domain;
largest contiguous S domain;
C/S interface count on the 48-cell ring.

Also retain the ordered 48-cell state snapshot
at the midpoint of every biased-periodic adverse burst.

These measurements are diagnostic only.
No new qualification threshold is inferred from them after results.

A persistent high min(C_fraction,S_fraction)
together with large opposed spatial domains
and low majority turnover
is the preregistered signature
of core/periphery deadlock.

RISK 3 — TIMESCALE DEPENDENCE

A41 intentionally contains no MEDIUM arm.

All six arms use the A40 SUBTRACTIVE_SLOW
committed-state law with rho = 3/4.

A40 already showed that MEDIUM
did not materially break the target oscillator.

Therefore A41 tests the recruitment-topology hypothesis
inside the slow-response regime only.

A41 cannot establish
that the mechanism generalizes to MEDIUM.

If A41 succeeds,
timescale generalization must be tested separately
rather than inferred.

ADDITIONAL COUNTER-PULSE TRAJECTORY MEASUREMENT

For biased-periodic contexts 44-47,
record C/S/U fractions at every epoch.

For each adverse burst report:

favored-side committed fraction at pulse onset;
minimum favored-side committed fraction during burst;
favored-side committed fraction at burst end;
recovery latency to the pre-pulse favored-side committed fraction,
or NEVER.

This separates:

core survives while periphery temporarily becomes U;

from:

the core itself continues eroding.

SPATIAL MIDPOINT SNAPSHOT

At the midpoint adverse epoch of every biased-periodic burst,
record the ordered 48-cell ring state:

C;
S;
U;
H.

Also record the corresponding
survivor-core membership mask.

This allows direct inspection
for a U moat between favored core
and opposing periphery
without changing the dynamics.

INSIDE / OUTSIDE RECRUITMENT MEASUREMENT

For every eligible U recruitment opportunity
during a biased-periodic adverse burst,
classify the cell as:

INSIDE:
within ring distance <= 3
of at least one favored-side survivor-core cell;

OUTSIDE:
not within ring distance <= 3
of any favored-side survivor-core cell.

Report separately:

opportunities;
adverse-side recruitments;
adverse-side recruitment rate;
mean base adverse lambda;
mean gated adverse lambda.

For BASE,
the same geometric classification is computed
without applying an exclusion multiplier.

This directly measures
whether exclusion suppresses opposing recruitment
where the mechanism claims it should.

OCCUPANCY VS MARGIN OSCILLATOR BREAK COUNT

For each D value report:

paired BASE biased-periodic oscillators;
number broken by OCCUPANCY_EXCLUSION;
number broken by MARGIN_EXCLUSION;
oscillators broken by both;
oscillators broken only by OCCUPANCY;
oscillators broken only by MARGIN.

This comparison is descriptive
in addition to the already frozen
MARGIN qualification requirement
that MARGIN biased-periodic oscillation
be lower than paired OCCUPANCY_EXCLUSION.

No post-result tie breaker is permitted.

PLAIN-SPEAK UPDATE

A41 is now asking two questions at once,
but in a way that keeps them separable.

First:

is it enough for an uncertain cell
to see that committed veterans are nearby?

That is OCCUPANCY.

Second:

should a deeply supported veteran
count more than a fresh commitment?

That is MARGIN.

If MARGIN wins,
the memory built in A39 and A40
has found a second job.

It is not only armor
that makes the veteran harder to knock over.

It becomes a signal
that tells the surrounding neighborhood:

this commitment has earned more local trust,
so do not rebuild the opposite side beside it
because of one short pulse.

But A41 also watches for the obvious danger.

A protective neighborhood can become a moat.

If the old core becomes so protected
that a real environmental reversal
cannot rebuild around it,
the organism has not become stable.
It has become rigid.

A41 also watches for a new failure mode:

the core stays one way,
the outer population becomes the other,
and the organism gets stuck split in two.

So success is not simply
fewer flips.

Success means:

the veteran core survives a short disturbance;

nearby opposing recruitment is selectively reduced;

the whole population stops rebuilding
the opposite army every few epochs;

balanced evidence does not manufacture a false winner;

and a real reversal can still replace
the old organization promptly.

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.


POST-F41 PRIMARY MANIFEST BINDING

DATE:
2026-09-22.

F41:
533b99503712bc37547969cf63100bd83336e69a

PRIMARY SEED:
A41-F41-533b99503712bc37547969cf63100bd83336e69a-PRIMARY

WORLD COUNT:
384.

WORLD SHAPE:
48 contexts x 8 replicas.

PRIMARY WORLD MANIFEST SHA256:
a902a20ee2222f6aebc451659d8910238a1c9ee1c74f37ee4eee69a018f761c1

STATUS:
BOUND BEFORE ANY PRIMARY ARM EXECUTION.

The manifest was derived from the frozen F41 source
after F41 existed.

No arm outcome,
population metric,
qualification result,
or scientific comparison
was observed before this binding.

The canonical DG-1R-05 primary is not consumed.

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.


A41 PRIMARY CLOSURE

DATE:
2026-09-22.

F41:
533b99503712bc37547969cf63100bd83336e69a

MANIFEST-BINDING COMMIT:
6e9fdd3cf1434737aea26fdb566957e4511e0847

PRIMARY SEED:
A41-F41-533b99503712bc37547969cf63100bd83336e69a-PRIMARY

PRIMARY WORLD MANIFEST SHA256:
a902a20ee2222f6aebc451659d8910238a1c9ee1c74f37ee4eee69a018f761c1

PRIMARY OUTPUT SHA256:
2ece0620dc75f451ceec767ab612805265f3bd64ec030ae053461a2c3969ecf2

PRIMARY RUNS:
2.

PRIMARY OUTPUT BYTES:
33457.

BYTE IDENTICAL:
true.

P38:
PASS.

All other executable integrity probes:
PASS.

A41_INFORMATION_GAIN:
FALSE.

QUALIFICATION

D2_MARGIN_EXCLUSION:
NOT QUALIFIED.

D3_MARGIN_EXCLUSION:
NOT QUALIFIED.

TECHNICAL EVIDENCE

D2 BASE SUBTRACTIVE SLOW:
aggregate service 235762;
harm rate 15.36%;
overall oscillation 11.20%;
biased-periodic oscillation 100.00%;
balanced false-majority 0.00%;
reversal acquisition 89.84%;
median old-majority loss 2 epochs;
core-adjacent adverse rebuild 20.31%.

D2 OCCUPANCY EXCLUSION:
aggregate service 236385;
harm rate 15.62%;
overall oscillation 10.68%;
biased-periodic oscillation 96.88%;
balanced false-majority 0.00%;
reversal acquisition 92.19%;
median old-majority loss 2 epochs;
core-adjacent adverse rebuild 16.32%.

D2 MARGIN EXCLUSION:
aggregate service 235790;
harm rate 15.62%;
overall oscillation 11.98%;
biased-periodic oscillation 100.00%;
balanced false-majority 0.00%;
reversal acquisition 91.41%;
median old-majority loss 2 epochs;
core-adjacent adverse rebuild 21.44%.

D3 BASE SUBTRACTIVE SLOW:
aggregate service 232314;
harm rate 16.15%;
overall oscillation 10.68%;
biased-periodic oscillation 96.88%;
balanced false-majority 0.00%;
reversal acquisition 87.50%;
median old-majority loss 2 epochs;
core-adjacent adverse rebuild 24.84%.

D3 OCCUPANCY EXCLUSION:
aggregate service 231943;
harm rate 14.84%;
overall oscillation 10.16%;
biased-periodic oscillation 96.88%;
balanced false-majority 0.00%;
reversal acquisition 88.28%;
median old-majority loss 2 epochs;
core-adjacent adverse rebuild 17.09%.

D3 MARGIN EXCLUSION:
aggregate service 231540;
harm rate 14.84%;
overall oscillation 9.64%;
biased-periodic oscillation 93.75%;
balanced false-majority 0.00%;
reversal acquisition 89.84%;
median old-majority loss 2 epochs;
core-adjacent adverse rebuild 20.69%.

BIASED-PERIODIC CONTEXT DETAIL

D2 BASE:
44 = 8/8 oscillatory;
45 = 8/8;
46 = 8/8;
47 = 8/8.

D2 OCCUPANCY:
44 = 8/8;
45 = 7/8;
46 = 8/8;
47 = 8/8.

D2 MARGIN:
44 = 8/8;
45 = 8/8;
46 = 8/8;
47 = 8/8.

D3 BASE:
44 = 7/8;
45 = 8/8;
46 = 8/8;
47 = 8/8.

D3 OCCUPANCY:
44 = 8/8;
45 = 8/8;
46 = 8/8;
47 = 7/8.

D3 MARGIN:
44 = 8/8;
45 = 7/8;
46 = 8/8;
47 = 7/8.

PAIRED OSCILLATOR BREAKS

D2:
BASE biased oscillators = 32;
broken by OCCUPANCY = 1;
broken by MARGIN = 0;
broken by both = 0;
OCCUPANCY-only = 1;
MARGIN-only = 0.

D3:
BASE biased oscillators = 31;
broken by OCCUPANCY = 1;
broken by MARGIN = 2;
broken by both = 0;
OCCUPANCY-only = 1;
MARGIN-only = 2.

These counts are far below
the frozen information-gain
and qualification thresholds.

LOCAL RECRUITMENT MECHANISM

D2 OCCUPANCY:
mean applied favored Q 0.27333;
all adverse-side recruitment 10.21%;
inside-core-radius adverse recruitment 6.17%;
outside-core-radius adverse recruitment 19.05%;
inside mean lambda suppression 31.62%;
high-Q adverse recruitment 2.42%;
low-Q adverse recruitment 18.33%.

D2 MARGIN:
mean applied favored Q 0.10927;
all adverse-side recruitment 11.75%;
inside-core-radius adverse recruitment 8.63%;
outside-core-radius adverse recruitment 18.80%;
inside mean lambda suppression 10.13%;
high-Q adverse recruitment 4.62%;
low-Q adverse recruitment 18.68%.

D3 OCCUPANCY:
mean applied favored Q 0.26195;
all adverse-side recruitment 9.80%;
inside-core-radius adverse recruitment 5.56%;
outside-core-radius adverse recruitment 18.80%;
inside mean lambda suppression 30.52%;
high-Q adverse recruitment 2.17%;
low-Q adverse recruitment 18.75%.

D3 MARGIN:
mean applied favored Q 0.10710;
all adverse-side recruitment 12.12%;
inside-core-radius adverse recruitment 8.15%;
outside-core-radius adverse recruitment 20.95%;
inside mean lambda suppression 10.50%;
high-Q adverse recruitment 3.15%;
low-Q adverse recruitment 20.61%.

Therefore both exclusion mechanisms
are locally active.

MARGIN_EXCLUSION shows the intended graded relation:
high-Q neighborhoods recruit to the adverse side
far less often than low-Q neighborhoods.

However OCCUPANCY applies a stronger field
under the frozen normalization
because each committed neighbor contributes 1
whereas MARGIN contributions are bounded below or equal to 1.

Therefore A41 does not justify the stronger claim
that evidence-depth information is intrinsically redundant
at the topology level.

It supports the narrower result:

under the frozen A41 equations,
plain occupancy produces stronger average exclusion,
while margin weighting produces selective graded exclusion
without a macro oscillator solution.

COUNTER-PULSE TRAJECTORY

D2 BASE:
mean favored committed fraction
0.7121 at pulse onset
to 0.2631 at burst end.

D2 OCCUPANCY:
0.7128
to 0.2591.

D2 MARGIN:
0.7177
to 0.2545.

D3 BASE:
0.6694
to 0.2474.

D3 OCCUPANCY:
0.6664
to 0.2473.

D3 MARGIN:
0.6555
to 0.2493.

The minimum committed fraction
is effectively the burst-end fraction
for all arms.

Thus exclusion reduces
who occupies nearby uncertain territory,
but it does not preserve
the favored committed population fraction
through the adverse burst.

This is the strongest mechanistic reason
A41 fails at the macro level.

SPATIAL / DEADLOCK DIAGNOSTICS

Biased-world final-eight-epoch diagnostics
show no persistent approximately 50/50
core/periphery deadlock signature.

Mean min(C_fraction,S_fraction):

D2 BASE 1.36%;
D2 OCCUPANCY 0.94%;
D2 MARGIN 1.30%;
D3 BASE 1.42%;
D3 OCCUPANCY 1.25%;
D3 MARGIN 1.29%.

Mean C/S interface count:

D2 BASE 0.410;
D2 OCCUPANCY 0.176;
D2 MARGIN 0.262;
D3 BASE 0.465;
D3 OCCUPANCY 0.219;
D3 MARGIN 0.359.

OCCUPANCY therefore reduces
opposed local interfaces,
but no stable two-domain deadlock emerges.

At adverse-burst midpoint,
roughly 71-73% of the frozen onset core
remains committed across arms.

Mean U occupancy at those midpoints
is about 12-16%,
with another roughly 9-10% in H.

This is not a clean impermeable moat.
It is a partially unresolved periphery
around a still-substantial surviving core.

MOAT / RIGIDITY CHECK

All arms retain reversal acquisition above 80%.

All arms retain median old-majority loss
at 2 epochs.

Balanced-periodic false-majority is 0%
for every arm.

Therefore A41 does not trade oscillation
for pathological rigidity.

RESEARCH-INSTRUMENTATION NOTE

The preregistered auxiliary metric:

time from true-reversal onset
until new-side recruitment near the old core
returns to the BASE same-context median rate

was not validly captured
at recruitment-opportunity resolution
by the frozen F41 output.

F41 records actual near-core recruitment events,
but not every eligible near-core opportunity
for the true-reversal families.

Therefore this one auxiliary diagnostic
is NOT VALIDLY MEASURED
and is not reconstructed post hoc.

No qualification or information-gain conclusion
depends on that metric.

This is treated as an instrumentation defect,
not as scientific evidence.

CAUSAL INTERPRETATION

A41 confirms the periphery-rebuild mechanism
at the local level.

A surviving core can suppress
nearby adverse recruitment.

The effect is large under OCCUPANCY:
inside-core-radius adverse recruitment
falls from 8.72% to 6.17% in D2
and from 10.26% to 5.56% in D3.

But local suppression is not sufficient
to stop the population oscillator.

The favored committed fraction
still collapses to roughly one quarter
of the population by adverse-burst end.

The exclusion field prevents some
opposing occupation of nearby U cells,
but it does not actively refill those cells
with the favored commitment.

Therefore A41 produces a fence,
not a regenerative core.

That directly justifies the next causal test:

positive active recruitment from the surviving core.

A42 should keep the core/periphery distinction,
but test whether veterans can act as a local magnet
for same-side recruitment.

A clean A42 lineage should distinguish:

active recruitment alone;

A41 exclusion alone;

and simultaneous push-pull
active recruitment plus exclusion.

If push-pull succeeds
where both individual mechanisms fail,
the missing behavior is synergistic population turnover control,
not another committed-state persistence transform.

PLAIN-SPEAK INTERPRETATION

A41 taught the core how to hold territory.

That part worked.

Near a surviving core,
fewer uncertain cells joined the attacking side.
The simple OCCUPANCY fence
was especially effective locally.

But the fence did not stop the organism
from flipping back and forth.

Why?

Because during a bad pulse,
the old side still shrank
from roughly two thirds or more of the population
to only about one quarter.

The fence kept some enemies out,
but it did not refill the empty ground
with allies.

There was no major moat failure.
The organism could still change its mind
when the world really changed.

There was also no stable 50/50 civil war
between core and periphery.

The failure is simpler:

defense without recruitment
is not enough.

So the next question is now unusually clean.

A42 should ask whether
the surviving core can actively recruit
nearby uncertain cells back onto its side.

A41:
hold the line.

A42:
bring reinforcements.

Then compare both together.

If the fence and the magnet
work only when combined,
we have identified a genuinely distributed
push-pull stabilization mechanism
rather than another stronger memory rule.

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.
