TITLE: LU-0B LU0BF1 FIVE-MANIFEST PRIMARY BINDING
DATE: 2026-09-23
STATUS: BOUND AFTER LU0BF1 / BEFORE ANY LU-0B PRIMARY TRAJECTORY
TRACK: DG-1 / LEARNED-UPDATER TRANSITION

LU0BF1:
3cbcb11042a177e76db8877a6e5d826aaa7aa9c7

FROZEN SOURCE:
bytes = 13906
sha256 = b2ef10e618871a081871d8858b3fcd153228cb831a643dc068bd3b30d9f6358f

PREREGISTRATION:
fc0332e5ab625e5aa05b931dbf47a43034760dfd

MECHANICAL GATE:
82b8fec283abcb0bf3e037d7227abe02b8deed18

PARENT V0.1:
4d3887fba0478bc1ef3bc4bea44f8e08582f5803

LU-0 CLOSURE:
074513c64a64318053fcbfcabdc9207202849063

TASK-1H CLOSURE:
1b848079ae0d54dd9e7b01c8d004a93b16aeb62d

REPLICATE COUNT:
5

No LU-0B primary trajectory executed before this binding.

DERIVATION

For k = 1..5:

replicate_key =
SHA1("LU0B-PREVALENCE|" + LU0BF1 + "|" + k)

task seed =
first 32 hex chars of
SHA256("LU0B-PRIMARY-SEED|" + LU0BF1 + "|" + k)

Programs, arrivals, corruption schedule,
distributed lesion, and anchors
are generated by the exact inherited Task-1 generators.

REPLICATE 1

replicate key:
69d8cd434a07f7714133ec4cdedb72a23f15e5f0

seed:
bd21a6125944c994e38fe947721bef53

programs:
21622;
53958;
10845;
53930

manifest SHA256:
6edaddd696797505e73a2a5c25d5b0c9dfb10ba4a799bcbb9890348012b71729

corrupt request ids:
54,84,88,89,95,115,144,149,189,269,285

lesion:
4,12,20,28,36,44,52,60

anchors 0-3:
C_IN 2; C_OUT 8; S_IN 42; S_OUT 36

anchors 4:
C_IN 18; C_OUT 24; S_IN 58; S_OUT 52

REPLICATE 2

replicate key:
c68a2db06271ced81c7abde3225b58183c21bb34

seed:
29fa0b34a58a2aabd8880ccbe48f9d80

programs:
18063;
22844;
9643;
50100

manifest SHA256:
709d725840a70d3f8eb3ee021f24902ac17091eac59ef6a497612277966193d0

corrupt request ids:
0,50,52,56,69,105,142,189,259,268,293,316

lesion:
5,13,21,29,37,45,53,61

anchors 0-3:
C_IN 3; C_OUT 9; S_IN 43; S_OUT 37

anchors 4:
C_IN 19; C_OUT 25; S_IN 59; S_OUT 53

REPLICATE 3

replicate key:
0147ddb576f8d804f5f1f6e6c894e6223d9bc1b4

seed:
be6f7849f0387739228b7e03f810b295

programs:
20669;
55857;
38204;
63558

manifest SHA256:
4e51886ea9835618852057b6382572de39a162425e5358d5555c1c404a5efd42

corrupt request ids:
19,43,68,80,82,100,117,120,158,179,206,217,254,257,299,305,315

lesion:
7,15,23,31,39,47,55,63

anchors 0-3:
C_IN 3; C_OUT 9; S_IN 43; S_OUT 37

anchors 4:
C_IN 19; C_OUT 25; S_IN 59; S_OUT 53

REPLICATE 4

replicate key:
d930cf5de0e89345bfdcd6a39908de982facb10c

seed:
d7a52c2cc53ddd333bd822ae6bec015b

programs:
52547;
46633;
30312;
44865

manifest SHA256:
3d3635c4d7a8035696bdfa9b2b809be845f472741ccac17f1d397ac2716790e7

corrupt request ids:
4,14,20,36,64,69,97,110,153,169,201,248,254,267,304,311

lesion:
6,14,22,30,38,46,54,62

anchors 0-3:
C_IN 4; C_OUT 10; S_IN 44; S_OUT 38

anchors 4:
C_IN 20; C_OUT 26; S_IN 60; S_OUT 54

REPLICATE 5

replicate key:
082a0a20c72aaec5cfb008b96ed055f98e8e96ea

seed:
405f9ad26e98bbcf422448c5a8734a09

programs:
14817;
52136;
20013;
27726

manifest SHA256:
cd44e8ea8b31aff75e90be184b4d90ea21b6d154ae26032a7ca47349fd3ba223

corrupt request ids:
3,11,19,39,71,78,82,107,121,143,197,223,229,255,263,294

lesion:
5,13,21,29,37,45,53,61

anchors 0-3:
C_IN 4; C_OUT 10; S_IN 44; S_OUT 38

anchors 4:
C_IN 20; C_OUT 26; S_IN 60; S_OUT 54

COMMON CONTRACT

Each world:
320 arrivals;
64 cells;
160 epochs;
D2;
R_TASK = 2;
G5_FULL = false;
LOCAL_HEDGE / V0.1 only;
request-bound handoff;
neutral sensing;
five 32-epoch phases;
+16 Phase-4 anchor relocation.

SERIALIZED FIVE-MANIFEST IDENTITY

bytes:
112238

SHA256:
61b79624854f9ad493ad04f6f3d1bc5fb0581e0f07dbf994ab9b156c24ab9823

BINDING RULE

All five worlds are fixed.

No world may be replaced.
No sixth world may be added.

No program, arrival, corruption, lesion, anchor,
pool equation, LOCAL_HEDGE equation, counterfactual,
TV threshold, rate threshold, prevalence threshold,
D family, G5 status, or interpretation rule
may change after this binding.

Two complete five-world prevalence sweeps
must be byte-identical before scientific interpretation.

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.
