TITLE: LU-0C LU0CF1 FIVE-MANIFEST PRIMARY BINDING
DATE: 2026-09-23
STATUS: BOUND AFTER LU0CF1 / BEFORE ANY LU-0C PRIMARY ARM EXECUTION
TRACK: DG-1 / LEARNED-UPDATER TRANSITION

LU0CF1:
872509a6da0935e791f458eca42d0d8741c9e200

FROZEN SOURCE:
bytes = 28556
sha256 = 57476bf302ad3117a496b5ffabb33f69d3a99d1d89eb683be2d6073c662d45ae

PREREGISTRATION:
408368910033ac2ad0fe4f65ded5a796030e296d

MECHANICAL GATE:
c1147ecb79de2c7f6bfee95f34d32d3301880b7d

PARENT V0.1:
4d3887fba0478bc1ef3bc4bea44f8e08582f5803

LU-0B CLOSURE:
c974b4def2973e72feec8b6be078c9255a0070d0

REPLICATE COUNT:
5

No LU-0C primary arm executed before this binding.

DERIVATION

For k = 1..5:

replicate_key =
SHA1("LU0C-LOCAL-POOL|" + LU0CF1 + "|" + k)

task seed =
first 32 hex chars of
SHA256("LU0C-PRIMARY-SEED|" + LU0CF1 + "|" + k)

Programs, arrivals, corruption schedule,
distributed lesion, and anchors
are generated by the exact inherited Task-1 generators.

REPLICATE 1

replicate key:
8e303bfb95ac4288a8ab6ea40a239d0515e2453d

seed:
28259a18d5a290831296e878e2ada9e5

programs:
25907;
5820;
13937;
59156

manifest SHA256:
149d57b0eea092f6aace173d051e979e3a02a236020700c2eb6f818c7334fc0c

corrupt request ids:
13,16,34,66,71,102,156,161,174,200,214,245,250,262,306

lesion:
2,10,18,26,34,42,50,58

anchors 0-3:
C_IN 6; C_OUT 12; S_IN 46; S_OUT 40

anchors 4:
C_IN 22; C_OUT 28; S_IN 62; S_OUT 56

REPLICATE 2

replicate key:
c0fc5236b78ee2a8627887845cd52ac1a1e1d9b5

seed:
aa552f997966c897b53f68f6c13298be

programs:
39544;
42329;
17755;
35483

manifest SHA256:
58b7d8d9b9f9ad4b5c99f505ac43e0c6604f247315a8a079f0b4abd5d27c7f7f

corrupt request ids:
9,64,84,99,118,158,179,182,314

lesion:
2,10,18,26,34,42,50,58

anchors 0-3:
C_IN 6; C_OUT 12; S_IN 46; S_OUT 40

anchors 4:
C_IN 22; C_OUT 28; S_IN 62; S_OUT 56

REPLICATE 3

replicate key:
fb53c8bc7ce31064070668cbee7cb0f46511e033

seed:
edb2493d5620832d087b89cb42d4266b

programs:
54563;
33722;
57958;
9686

manifest SHA256:
40cca3ba537ff86ddc7d3b3dd6a48393e254d532058f1bd0c20b4c05460ad754

corrupt request ids:
29,70,125,133,138,146,152,230,245,272,291,306,309

lesion:
4,12,20,28,36,44,52,60

anchors 0-3:
C_IN 4; C_OUT 10; S_IN 44; S_OUT 38

anchors 4:
C_IN 20; C_OUT 26; S_IN 60; S_OUT 54

REPLICATE 4

replicate key:
500f516c638dbca6983fc68ab9a0040bd5973103

seed:
56cd0ebcf153380da71ccab8fd87e790

programs:
36188;
16148;
59954;
62486

manifest SHA256:
8035ed142a0e1a307bfc873624d7ccd312e6a5f37a63751c284354e2e112763d

corrupt request ids:
4,13,32,70,113,116,130,145,167,205,218,224,231,295,296,319

lesion:
6,14,22,30,38,46,54,62

anchors 0-3:
C_IN 1; C_OUT 7; S_IN 41; S_OUT 35

anchors 4:
C_IN 17; C_OUT 23; S_IN 57; S_OUT 51

REPLICATE 5

replicate key:
598bd2825276e107360c7edab41d8992139a5aef

seed:
c429ae52e7ff28978554bfaaff386426

programs:
30855;
46417;
17022;
54482

manifest SHA256:
96e7988427aadd03e69b09cc417a5b9924024ef378b1675fca6806d8fd838e00

corrupt request ids:
3,6,11,25,54,92,94,108,120,124,140,193,217,238,246,257,290

lesion:
1,9,17,25,33,41,49,57

anchors 0-3:
C_IN 4; C_OUT 10; S_IN 44; S_OUT 38

anchors 4:
C_IN 20; C_OUT 26; S_IN 60; S_OUT 54

COMMON CONTRACT

Each world:
320 arrivals;
64 cells;
160 epochs;
D2;
R_TASK = 2;
G5_FULL = false;
V0.1 LOCAL_HEDGE;
A45 ECHO_PHASE;
request-bound handoff;
neutral sensing;
same three-arm paired manifest;
five 32-epoch phases;
+16 Phase-4 anchor relocation.

SERIALIZED FIVE-MANIFEST IDENTITY

bytes:
112193

SHA256:
23a8aed3ea7b9af564e158c9ebba1da4cd09aa384392fede4be516bb51cd2dee

FRESHNESS CHECK

The five LU-0C manifest SHA256 identities
were compared against all five bound manifests from:

Task-1F R1;
Task-1H;
LU-0B.

Collisions:
0.

BINDING RULE

All five worlds are fixed.

No world may be replaced.
No sixth world may be added.

No program, arrival, corruption, lesion, anchor,
local-pool radius, local-pool normalization,
pool rho, pool source, LOCAL_HEDGE equation,
ECHO_PHASE equation, success threshold,
or interpretation rule may change after this binding.

Two complete five-world x three-arm sweeps
must be byte-identical before scientific interpretation.

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.
