TITLE: LU-0D LU0DF1 FIVE-MANIFEST PRIMARY BINDING
DATE: 2026-09-23
STATUS: BOUND AFTER LU0DF1 / BEFORE ANY LU-0D PRIMARY ARM EXECUTION
TRACK: DG-1 / LEARNED-UPDATER TRANSITION

PREREGISTRATION:
ab9afc0db2b5717ee27541dce1a37c276c950610

MECHANICAL GATE:
f25e7ff04391f6eabc05e8bb1b4eee478dcd83a1

LU0DF1:
f23888e37fce4b19a65403dafe27f8a8848b8600

PARENT LU0CF1:
872509a6da0935e791f458eca42d0d8741c9e200

LU-0C CLOSURE:
2356cdb49171a1144c3f56a28ba9d29a47f42796

FROZEN SOURCE:
bytes = 13990
sha256 = 16bd83660cee18d71ea2a26a48032d1a376dee2f9f9a8ad0a1e1b21bb0d23440

REPLICATE COUNT:
5

No LU-0D primary arm executed before this binding.

DERIVATION

For k = 1..5:

replicate_key =
SHA1("LU0D-NO-POOL-CONFIRM|" + LU0DF1 + "|" + k)

task seed =
first 32 hex characters of
SHA256("LU0D-PRIMARY-SEED|" + LU0DF1 + "|" + k)

Programs, arrivals, corruption schedule,
distributed lesion, and anchors
are generated by the exact inherited Task-1 generators.

REPLICATE 1

replicate key:
2a7390df5bf1507fd7141b898be62fe18368d0f9

seed:
07cbb15a13dcbb82b9c8cc049802fe87

programs:
18222;
17207;
41782;
44896

manifest SHA256:
3bdf242795bfcc59b17e425a5b9f6a5b49e53aaa581731ae4bbf4c320cdfc9dc

corrupt request ids:
7,38,49,87,88,224,228,242,290,310,312

lesion:
1,9,17,25,33,41,49,57

anchors 0-3:
C_IN 0; C_OUT 6; S_IN 40; S_OUT 34

anchors 4:
C_IN 16; C_OUT 22; S_IN 56; S_OUT 50

REPLICATE 2

replicate key:
6fc1b9688977609f04fac6d5fd38c5506188c994

seed:
101cd9a71d5874fe9922967ca692a6c4

programs:
44385;
28422;
18318;
8607

manifest SHA256:
175cf0998a1bcc3e34491120b36841ccdba8c1de0b8176f3e7d81c09aada7348

corrupt request ids:
6,36,40,47,74,132,145,158,184,191,216,254,263,269,278,310,313

lesion:
7,15,23,31,39,47,55,63

anchors 0-3:
C_IN 0; C_OUT 6; S_IN 40; S_OUT 34

anchors 4:
C_IN 16; C_OUT 22; S_IN 56; S_OUT 50

REPLICATE 3

replicate key:
222a37b27a24c85b386b13dd754260dde5a68539

seed:
c76fb4e2fa370b4102d2248869db1892

programs:
45777;
26195;
61575;
50361

manifest SHA256:
5161d980953779e175b567d181794a6644a8924bdb046677d2a2e17cda3daeba

corrupt request ids:
17,31,65,94,95,112,124,152,160,166,179,181,210,216,299,317,319

lesion:
3,11,19,27,35,43,51,59

anchors 0-3:
C_IN 5; C_OUT 11; S_IN 45; S_OUT 39

anchors 4:
C_IN 21; C_OUT 27; S_IN 61; S_OUT 55

REPLICATE 4

replicate key:
98b0983308db38cdb5c2d39fa799725a9d80d49e

seed:
dc9b6d5cb203b41e9c0a1cecde0e9db5

programs:
52494;
55664;
22772;
61848

manifest SHA256:
ee75dbda081ca8359eba49c39e1b9d80cd5f9ae75c8969ca25ca50126e4dff07

corrupt request ids:
12,13,14,106,117,134,139,156,171,197,200,206,248,257,269,271

lesion:
4,12,20,28,36,44,52,60

anchors 0-3:
C_IN 5; C_OUT 11; S_IN 45; S_OUT 39

anchors 4:
C_IN 21; C_OUT 27; S_IN 61; S_OUT 55

REPLICATE 5

replicate key:
9a6ba49d8d13fd1851c9408b0cab6f7b0796688b

seed:
2e46b0838550ef81721331a6175ff47f

programs:
4601;
63024;
36561;
35533

manifest SHA256:
0c767b3c8e77284cb485a47324262608c0c71fdc498842c8464578d13b2f08b6

corrupt request ids:
22,121,137,197,208,224,236,238,251,258,274,284,292,294,300,318

lesion:
1,9,17,25,33,41,49,57

anchors 0-3:
C_IN 0; C_OUT 6; S_IN 40; S_OUT 34

anchors 4:
C_IN 16; C_OUT 22; S_IN 56; S_OUT 50

COMMON CONTRACT

Each world:
320 arrivals;
64 cells;
160 epochs;
D2;
R_TASK = 2;
G5_FULL = false;
V0.1 LOCAL_HEDGE;
A45 ECHO_PHASE;
request-bound handoff;
neutral sensing;
same paired manifest;
five 32-epoch phases;
+16 Phase-4 anchor relocation.

SERIALIZED FIVE-MANIFEST IDENTITY

bytes:
111942

SHA256:
41370cfc7b904dedda6737124e742f45169c60b768328905440a67573aae1454

FRESHNESS CHECK

Compared against all five bound manifests from:
Task-1F R1;
Task-1H;
LU-0B;
LU-0C.

prior manifest identities checked:
20.

collisions:
0.

BINDING RULE

All five worlds are fixed.

No world may be replaced.
No sixth world may be added.

No program, arrival, corruption, lesion, anchor,
NO_POOL equation, V0.1 equation,
LOCAL_HEDGE equation, ECHO_PHASE equation,
success threshold, or interpretation rule
may change after this binding.

Two complete five-world x two-arm sweeps
must be byte-identical before scientific interpretation.

canonical_scientific_execution = false.
stab18_r1_touched = false.
DG1R05_CANONICAL_PRIMARY_CONSUMED = false.
